import { FirstLevelEntityType } from './types/projectTypes';

export const entityModel: FirstLevelEntityType[] = [
	{
		equipmentCosts: 25000,
		estimatedProfit: 36000,
		id: 1,
		machineOperatorSalary: 0,
		mainCosts: 0,
		materials: 0,
		mimExploitation: 0,
		overheads: 25000,
		rowName: 'Южная строительная площадка',
		salary: 34000,
		supportCosts: 0,
		total: 0,
		parentId: null,
		isEdited: false,
		child: [
			{
				equipmentCosts: 25000,
				estimatedProfit: 36000,
				id: 2,
				machineOperatorSalary: 0,
				mainCosts: 0,
				materials: 0,
				mimExploitation: 0,
				overheads: 25000,
				rowName: 'Фундаментальные работы',
				salary: 34000,
				supportCosts: 0,
				total: 0,
				parentId: 1,
				isEdited: false,
				child: [
					{
						equipmentCosts: 25000,
						estimatedProfit: 36000,
						id: 4,
						machineOperatorSalary: 0,
						mainCosts: 0,
						materials: 0,
						mimExploitation: 0,
						overheads: 25000,
						rowName: 'Фундаментальные работы',
						salary: 34000,
						supportCosts: 0,
						total: 0,
						parentId: 2,
						isEdited: false,
					},
					{
						equipmentCosts: 25000,
						estimatedProfit: 36000,
						id: 5,
						machineOperatorSalary: 0,
						mainCosts: 0,
						materials: 0,
						mimExploitation: 0,
						overheads: 25000,
						rowName: 'Фундаментальные работы',
						salary: 34000,
						supportCosts: 0,
						total: 0,
						parentId: 2,
						isEdited: false,
					},
				],
			},
			{
				equipmentCosts: 25000,
				estimatedProfit: 36000,
				id: 3,
				machineOperatorSalary: 0,
				mainCosts: 0,
				materials: 0,
				mimExploitation: 0,
				overheads: 25000,
				rowName: 'Самые фундаментальные работы',
				salary: 34000,
				supportCosts: 0,
				total: 0,
				parentId: 1,
				isEdited: false,
				child: [],
			},
		],
	},
];
